# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('CANCELED', 'canceled')], default='canceled', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
