# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 03:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180826_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
